"""initial_migration

Revision ID: 29efaef05c8d
Revises: 
Create Date: 2025-09-27 00:32:09.128218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29efaef05c8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=False),
    sa.Column('kpi_nome', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_id'), 'metas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.Text(), nullable=True),
    sa.Column('dados_depois', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_tabela_timestamp', 'audit_log', ['tabela', 'timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('comercial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=False),
    sa.Column('produto', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('leads_recebidos', sa.Integer(), nullable=True),
    sa.Column('contatos_realizados', sa.Integer(), nullable=True),
    sa.Column('propostas_enviadas', sa.Integer(), nullable=True),
    sa.Column('vendas_fechadas', sa.Integer(), nullable=True),
    sa.Column('valor_vendas', sa.Float(), nullable=True),
    sa.Column('ticket_medio', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comercial_unique', 'comercial_data', ['data_ref', 'vendedor', 'produto'], unique=False)
    op.create_index(op.f('ix_comercial_data_id'), 'comercial_data', ['id'], unique=False)
    op.create_table('eventos_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('evento', sa.String(length=200), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.String(length=50), nullable=True),
    sa.Column('inscricoes', sa.Integer(), nullable=True),
    sa.Column('participantes', sa.Integer(), nullable=True),
    sa.Column('no_shows', sa.Integer(), nullable=True),
    sa.Column('leads_gerados', sa.Integer(), nullable=True),
    sa.Column('custo_evento', sa.Float(), nullable=True),
    sa.Column('receita_evento', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eventos_unique', 'eventos_data', ['data_ref', 'evento'], unique=False)
    op.create_index(op.f('ix_eventos_data_id'), 'eventos_data', ['id'], unique=False)
    op.create_table('financeiro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=True),
    sa.Column('receitas', sa.Float(), nullable=True),
    sa.Column('despesas', sa.Float(), nullable=True),
    sa.Column('contas_receber', sa.Float(), nullable=True),
    sa.Column('contas_pagar', sa.Float(), nullable=True),
    sa.Column('inadimplencia', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_financeiro_unique', 'financeiro_data', ['data_ref', 'categoria', 'subcategoria'], unique=False)
    op.create_index(op.f('ix_financeiro_data_id'), 'financeiro_data', ['id'], unique=False)
    op.create_table('marketing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False, comment='Data de referência do dado'),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('campanha', sa.String(length=200), nullable=False),
    sa.Column('investimento', sa.Float(), nullable=False, comment='Valor sem símbolo R$'),
    sa.Column('impressoes', sa.Integer(), nullable=True),
    sa.Column('cliques', sa.Integer(), nullable=True),
    sa.Column('conversoes', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('vendas', sa.Integer(), nullable=True),
    sa.Column('receita', sa.Float(), nullable=True, comment='Valor sem símbolo R$'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketing_unique', 'marketing_data', ['data_ref', 'canal', 'campanha'], unique=False)
    op.create_index(op.f('ix_marketing_data_id'), 'marketing_data', ['id'], unique=False)
    op.create_table('pedagogico_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('curso', sa.String(length=200), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=True),
    sa.Column('turma', sa.String(length=100), nullable=True),
    sa.Column('alunos_matriculados', sa.Integer(), nullable=True),
    sa.Column('alunos_ativos', sa.Integer(), nullable=True),
    sa.Column('evasao', sa.Integer(), nullable=True),
    sa.Column('conclusoes', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Float(), nullable=True),
    sa.Column('satisfacao', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pedagogico_unique', 'pedagogico_data', ['data_ref', 'curso', 'turma'], unique=False)
    op.create_index(op.f('ix_pedagogico_data_id'), 'pedagogico_data', ['id'], unique=False)
    op.create_table('rh_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('funcionarios_ativos', sa.Integer(), nullable=True),
    sa.Column('novas_contratacoes', sa.Integer(), nullable=True),
    sa.Column('desligamentos', sa.Integer(), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=True),
    sa.Column('horas_extras', sa.Float(), nullable=True),
    sa.Column('treinamentos_realizados', sa.Integer(), nullable=True),
    sa.Column('participantes_treinamento', sa.Integer(), nullable=True),
    sa.Column('custo_folha', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rh_unique', 'rh_data', ['data_ref', 'departamento'], unique=False)
    op.create_index(op.f('ix_rh_data_id'), 'rh_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rh_data_id'), table_name='rh_data')
    op.drop_index('idx_rh_unique', table_name='rh_data')
    op.drop_table('rh_data')
    op.drop_index(op.f('ix_pedagogico_data_id'), table_name='pedagogico_data')
    op.drop_index('idx_pedagogico_unique', table_name='pedagogico_data')
    op.drop_table('pedagogico_data')
    op.drop_index(op.f('ix_marketing_data_id'), table_name='marketing_data')
    op.drop_index('idx_marketing_unique', table_name='marketing_data')
    op.drop_table('marketing_data')
    op.drop_index(op.f('ix_financeiro_data_id'), table_name='financeiro_data')
    op.drop_index('idx_financeiro_unique', table_name='financeiro_data')
    op.drop_table('financeiro_data')
    op.drop_index(op.f('ix_eventos_data_id'), table_name='eventos_data')
    op.drop_index('idx_eventos_unique', table_name='eventos_data')
    op.drop_table('eventos_data')
    op.drop_index(op.f('ix_comercial_data_id'), table_name='comercial_data')
    op.drop_index('idx_comercial_unique', table_name='comercial_data')
    op.drop_table('comercial_data')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_tabela_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metas_id'), table_name='metas')
    op.drop_table('metas')
    # ### end Alembic commands ###
